import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'FBI',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {children}
        <div className='fixed right-[1rem] bottom-[1rem]'>
          <Link href='/'>
            <div className='px-[1rem] py-[0.5rem] bg-slate-600 text-white rounded-lg active:translate-y-[4px]'>
              Home
            </div>
          </Link>
        </div>
      </body>
    </html>
  );
}
